### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by yangenshen** [davidhallac/TICC#12]
I saw that your traing data 
`idx_k = training_indices[i+k]`
`complete_D_train[i][k*n:(k+1)*n] =  Data[idx_k][0:n]`
so the data is not continuous? for example your training_indices is ...10,11,13,14,16..., there would be one  complete_D_train: 10-11-13-14-16. According to my understanding of the article, it should be 10-11-12-13-14-15, 11-...-16, 13-...-18... . Any problems with my understanding?

**Comment by davidhallac** [comment]
That code is there in case you want to remove some time stamps for testing purposes. In the existing TICC solver, training_percent is 100% (see TICC/src/TICC_helper.py), so you are correct in believing that the existing TICC solver assumes the data is continuous.
