### ISSUE TITLE
Example stops at iteration zero

### ISSUE THREAD

**Issue by elmiraberjisian** [davidhallac/TICC#17]
Hi
Could you please help me with this.
As I tried to run example, I constantly received similar result: it printed ITERATION ### 0 and did not proceed. I will be beyond grateful if you could help me figuring out what is going wrong.

**Comment by davidhallac** [comment]
Hmm, can you provide more context? What OS are you running it on, can you print the terminal output when you run the code?

**Comment by elmiraberjisian** [comment]
Using Python 2.7.14 64-bit on Windows 10
The code prints out this line
print "\n\n\nITERATION ###", iters 
when iters=0
and then does not print anything. The python process hangs and cannot be terminated even with the task manager.

**Comment by davidhallac** [comment]
I know that the multiprocessing package can have strange issues with Windows, but unfortunately I don't have access to a Windows machine at the moment to try it on (I just ran it on my mac and it works fine)

Do you have a Mac/Linux machine to try running it on instead? If not, is there any way you can let me know at which line it gets stuck at in the code (using print statements/etc) on Windows?

**Comment by elmiraberjisian** [comment]
I set up virtual machine and implement the code in Linux it worked. I appreciate your help.

**Comment by davidhallac** [comment]
Great!
