### ISSUE TITLE
fewer data points

### ISSUE THREAD

**Issue by elmiraberjisian** [davidhallac/TICC#19]
I noticed that in example.py, clustered points are fewer  by window size than main input data(i.e., output=input-windowsize) could you please help me identify which points are excluded?and why these points are excluded? I keenly appreciate your time.

**Comment by davidhallac** [comment]
Yes, that is correct. If the window is size W, our solver excludes the first W points from the clustered dataset (since it does not have enough info to properly cluster these first W points, since their window goes back beyond the beginning of the dataset...).
