### ISSUE TITLE
NameError: name 'TUNGraph' is not defined

### ISSUE THREAD

**Issue by Matrixio** [davidhallac/TICC#2]
can not run code.  show the issue : "NameError: name 'TUNGraph' is not defined "
python version 2.7
can not install TUNGraph by 'pip install TUNGraph'

**Comment by davidhallac** [comment]
Hi,

TUNGraph comes from the Snap.py package, which you can download here: https://snap.stanford.edu/snappy/. Thanks!

**Comment by maxwell13** [comment]
I still have this issue after  pip install snap-stanford
