### ISSUE TITLE
data.tsv problem in car.py

### ISSUE THREAD

**Issue by yashao** [davidhallac/TICC#24]
Hello!
     I'm very interested in your paper, and want to study your TICC algorithm, but the data.tsv file is missing in the car.py file, is it convenient to share the data?
    thank you very much!

**Comment by yuyingg0921** [comment]
The same question as #13 ~

**Comment by davidhallac** [comment]
Hi, as per #13, the dataset for the car example is unfortunately proprietary, and it was provided to us on the condition that we do not share it publicly. Sorry for any inconvenience!
