### ISSUE TITLE
Betweeness Score 

### ISSUE THREAD

**Issue by elmiraberjisian** [davidhallac/TICC#26]
Hi David
I appreciate your paper, it is so promising. I already applied it on my data set and got good result. But for identification of clusters and make it more reproducible i need to calculate betweenness score and look if my clusters have "signature". I will be really grateful if you could provide calculation of betweenness score code in example as I am very new to python.

**Comment by davidhallac** [comment]
Hi! 

As explained in #15 (https://github.com/davidhallac/TICC/issues/15), we used Snap.py to calculate the between-ness scores. We also included some code in the answer to that question that can be used to calculate the exact betweenness scores.
