### ISSUE TITLE
miss dataset for car.py

### ISSUE THREAD

**Issue by mikewin** [davidhallac/TICC#3]
car.py will read "data.tsv", 

where is this file?

Thanks!

**Comment by sagarvare** [comment]
Unfortunately the car dataset is proprietary and cannot be released. The results of running the TICC algorithm on the dataset are added in the paper.

**Comment by davidhallac** [comment]
Just to add one more quick note on top of this, while we are unable to release the real-world dataset, you can generate synthetic data to run the car.py code (or any other file) using "generate_synthetic_data.py".

In generate_synethetic_data, the relevant parameters to tweak are in lines 6-12 to generate different types of data.
