### ISSUE TITLE
Why there have edges between blue layer and orange layer in the figure 1?

### ISSUE THREAD

**Issue by GMorGAME** [davidhallac/TICC#38]
![figure](https://user-images.githubusercontent.com/34540163/40064130-76cf70de-5891-11e8-9f57-3a5d180a3d96.jpg)
The  figure   in the TICC paper ,you said each cluster is characterized by a correlation network, or MRF, defined over a short window of size w，so the  layer at time t might effect the other layer at time t+1, just like thera are   edges between blue layer and purple layer or purple layer and orange layer.
But as MRF network defined, why there are edges between blue and orange layer in cluster A?I can't understand。I hope you can help me.Tanks.

**Comment by davidhallac** [comment]
Hi, thank you for your question! The edges between the blue are orange are the "two-step" edges (and occur if the window size is 3 or larger). Essentially, the window size determines how many layers the edges can cut across, so the blue/orange edges say that a certain sensor at time "t" affects a different sensor at time "t+2".

Hope that helps clarify things!
