### ISSUE TITLE
different BIC with same parameters

### ISSUE THREAD

**Issue by elmiraberjisian** [davidhallac/TICC#39]
I run example with same parameters 3 times and I am getting different BICs. Initially, I wanted to try different number of clusters and based on minimum BIC, identify number of clusters and that was when I found out that every run with same parameters and dataset yielded different BICs. Could you please explain why BIC vary while parameters and data are the same.

**Comment by davidhallac** [comment]
Hmm, that definitely shouldn’t be happening. Are you sure you’ve pulled the newest version of the code? This might have to do with issue #30 , where we used a different random seed every time we ran TICC. Can you try re-pulling and running again? Thanks!

**Comment by elmiraberjisian** [comment]
I used the new version and it is resolved. Thanks!

**Comment by davidhallac** [comment]
Great, glad that fixed it!
