### ISSUE TITLE
computeF1_macro  meet a problem

### ISSUE THREAD

**Issue by mikewin** [davidhallac/TICC#4]
In function computeF1_macro :
TP= permuted_confusion_matrix[cluster,cluster]
when TP =0.0 and FP=0.0, can't get F1_score.

when train_confusion_matrix_EM =
[[0.0000 179.0000 0.0000]
 [0.0000 182.0000 0.0000]
 [0.0000 180.0000 0.0000]]
this line cause problem
f1_EM_tr = computeF1_macro(train_confusion_matrix_EM,matching_EM,num_clusters)

BTW:
It 's seems something wrong after/during smooth algorithm

console output :

completed solving the optimization problem for the cluster
printing the cluster len
length of the cluster  0 ------> 169
length of the cluster  1 ------> 186
length of the cluster  2 ------> 186
beginning with the DP - smoothening ALGORITHM
completed smoothening algorithm
printing the length of points in each cluster
length of cluster # 0 --------> 0
length of cluster # 1 --------> 541
length of cluster # 2 --------> 0
...
The binary accuracy at the end of iteration is: 0.42 0.5 0.42

Run Steps:
python generate_synthetic_data.py
python TICC.py
not changed any parameters

Thanks

**Comment by davidhallac** [comment]
It seems like we set the Beta parameter in TICC.py too high, so it by default assigned all the points to just one cluster (at which point it doesn't make sense to measure F_1 score, so the code doesn't handle the corner case).

I just updated the default Beta parameter in TICC.py, so if you pull the newest version and run the same code, it should work without any errors now. 

Thanks for letting us know!
