### ISSUE TITLE
Visualization Function

### ISSUE THREAD

**Issue by GVKannan** [davidhallac/TICC#40]
Could you please define the working of Visualization function. I would visualize a custom data time series with 1440 but I cannot understand the parameters: Matrix_v, stock_number, time_steps, y_ticks. Please do elaborate on the same.

Best,
Vignesh

**Comment by davidhallac** [comment]
Hi Vignesh,

That was legacy code from the paper, which we did not end up using for the final plots. Essentially, it just plots out a m-by-n grid graph with edges corresponding to non-zero elements in the inverse covariance matrix. Stock_number refers to the individual sensor you want to plot (it is -1 for all sensors). Time steps in the window size, y_ticks are the sensors names, and file_name is the output file to save it to.

Hope that helps!
