### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GaussianMixture'

### ISSUE THREAD

**Issue by shujamughal** [davidhallac/TICC#43]
Hi,
When I try to run the example code, I got the error. here is the output.

shuja@shujamughal:~/Desktop/data/bsc_data/year_3/TICC$ python example.py 
('lam_sparse', 0.11)
('switch_penalty', 600)
('num_cluster', 8)
('num stacked', 1)
completed getting the data
Traceback (most recent call last):
  File "example.py", line 8, in <module>
    (cluster_assignment, cluster_MRFs) = ticc.fit(input_file=fname)
  File "/home/shuja/Desktop/data/bsc_data/year_3/TICC/TICC_solver.py", line 75, in fit
    gmm = mixture.GaussianMixture(n_components=self.number_of_clusters, covariance_type="full")
AttributeError: 'module' object has no attribute 'GaussianMixture'

**Comment by shujamughal** [comment]
solved

**Comment by JeremyHieulleCode** [comment]
How did you solved it?
