### ISSUE TITLE
error -  No such file or directory: 'LICENSE.md'

### ISSUE THREAD

**Issue by yoganandamc** [davidhallac/TICC#49]
I am getting the below error while installing the package. COuld you please resolve this issue.
 error: [Errno 2] No such file or directory: 'LICENSE.md'

**Comment by davidhallac** [comment]
How are you trying to install the package? Using "git clone git@github.com:davidhallac/TICC.git" seems to work for me, and does not throw any errors

**Comment by yoganandamc** [comment]
Hi, 
Thanks you so much for your reply. 
I have downloaded the TICC-0.1.6.tar.gz file and installing through pip install.  Please let me know if i need to try other ways.

**Comment by davidhallac** [comment]
Please use Github, not pip, to install the TICC package. That will resolve your issue - thanks!
