### ISSUE TITLE
No module named 'TICC_solver'

### ISSUE THREAD

**Issue by yoganandamc** [davidhallac/TICC#50]
Hi

I am getting the below error while running the following script. from TICC_solver import TICC

ModuleNotFoundError: No module named 'TICC_solver'

I am able to import TICC sucessfully. But having problem with TICC_solver. Could you please help me.

I have installed TICC using "git clone git@github.com:davidhallac/TICC.git"

Thanks,

**Comment by yoganandamc** [comment]
Hi,

I liked this methodology and cant wait to implement. I have sensors data and wanted to implement this algorithm. Could you please provide me the solution for the above error. Your quick response will be highly appreciated.

Thanks,

**Comment by davidhallac** [comment]
Hi! That is most likely because you are running the code from the wrong directory. Please place your code inside the TICC directory, then when you run it, it will see TICC_solver and be able to run. Thanks!
