### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by yoganandamc** [davidhallac/TICC#51]
Hi, 

I am getting a new error 'ModuleNotFoundError: No module named 'src''. Please let me know how I can resolve this. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\127791\AppData\Local\Continuum\anaconda3\TICC\TICC_solver.py", line 11, in <module>
    from src.TICC_helper import *
ModuleNotFoundError: No module named 'src'

**Comment by davidhallac** [comment]
Hi! This stems from the same error as #50, where it appears your code is running in the wrong directory. "src" is a folder in the TICC directory, so if you haven't changed anything, TICC_solver should be able to find it. For example, you can create a script called runTICC.py (and put it in the TICC directory, similar to example.py), and it should be able to find "src". Thanks!
