### ISSUE TITLE
Create a training video

### ISSUE THREAD

**Issue by yoganandamc** [davidhallac/TICC#52]
Hi,

I have a request for you. Is it possible to create a YouTube training video which explains the complete concept with an example and how to interpret the results and also the comparison with other clustering algorithms. 

As of now I am going through your article. But it will be good if we get a training video. 

Thanks for your help,

**Comment by NofelYaseen** [comment]
Video illustration: https://www.youtube.com/watch?v=Fh5fRiRd3Q4
Presentation: https://www.youtube.com/watch?v=QYUyAbuHrSs

**Comment by yamunanr** [comment]
I have an issue in the code... while I run the code on my windows machine,  multiprocessing is unable to process.. is there a workaround for running code in windows?
