### ISSUE TITLE
"NameError: global name 'GenRndGnm' is not defined" when running generate_synthetic_data.py

### ISSUE THREAD

**Issue by csjzhou** [davidhallac/TICC#7]
I am working in Anaconda and creating a Python2.7 environment. I also installed snap with "pip install snap". But when I run "python generate_synthetic_data.py", I got the error "NameError: global name 'GenRndGnm' is not defined". I also tried to install snap with "python setup.py install" by downloading snap from its homepage and got same errors. May I know any of your solutions?

**Comment by davidhallac** [comment]
Hi, GenRndGnm is in the "snap" package. What is the error you get when you try to install Snap from here: https://snap.stanford.edu/snappy/?

**Comment by csjzhou** [comment]
When I install "snap", it looks fine as the following message (I installed snap before and this is a retry and so we see the "Removing" in the following message):
(py27) C:\work\snap-4.0.0-4.0-Win-x64-py2.7>python setup.py install
running install
running build
running build_py
creating build
creating build\lib
copying snap.py -> build\lib
running install_lib
running install_data
running install_egg_info
Removing C:\Anaconda3\envs\py27\Lib\site-packages\snap-4.0.0_dev_Win_x64_py2.7-p
y2.7.egg-info
Writing C:\Anaconda3\envs\py27\Lib\site-packages\snap-4.0.0_dev_Win_x64_py2.7-py
2.7.egg-info

I am using Anaconda3 and create a Python 2.7 environment to run TICC on Windows7. I also tried on Ubuntu 16 and got the same error message.

**Comment by csjzhou** [comment]
I solved this problem!
I clean the previously installed SNAP and reinstall it. It works now.
Thank you very much!
