### ISSUE TITLE
"lle" in TICC.py

### ISSUE THREAD

**Issue by csjzhou** [davidhallac/TICC#9]
I am trying to understand the TICC code for the KDD’17 paper and have a question as following:
In TICC.py:
Line 539:
lle = np.dot(   x.reshape([1,(num_blocks-1)*n]), np.dot(inv_cov_matrix,x.reshape([n*(num_blocks-1),1]))  ) + log_det_cov
 
May I know whether “lle” refers to the equation (2) in the paper? If yes, is a minus “-” necessary before the first np.dot() because of the equation (2) in the paper?

**Comment by davidhallac** [comment]
The LLE in TICC.py is actually the negative LLE (so the negative of equation 2). Note that the log_det_cov term is equal to:

log_det_cov = log (det (sigma))
		= log (det (theta^-1))
		= log (1 / det(theta))
		= - log (det (theta))

So, log_det_cov = - log det (theta), which turns line 539 of the code into the negative LLE.

Hopefully that helps clarifies things!

**Comment by csjzhou** [comment]
Great! Thank you very much!
